# Site settings
author: Chris
title: A hero's story. 
header-img: img/home-bg.png
email: chrisxcheong@gmail.com
copyright_name: Chris
description: > # this means to ignore newlines until "baseurl:"
  Rather
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  PowerPuppy

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
